name: Format and test
on: [pull_request]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
      - name: Prettier code
        run: npm run format
      - name: Install Angular CLI
        run: npm i --silent @angular/cli
      - name: Run tests
        run: npm run test
